### ISSUE TITLE
Scaffolded "theme-tests" don't load theme when running phpunit in single site

### ISSUE THREAD

**Issue by mboynes** [wp-cli/scaffold-command#114]
In attempting to use tests from the `theme-tests` base that `wp scaffold` sets up, none of my theme's functions existed. Assuming I was doing something wrong, I created [a minimal theme](https://github.com/mboynes/theme-tests/) and ran `wp scaffold theme-tests` to generate the tests. In [the theme's `functions.php` file](https://github.com/mboynes/theme-tests/blob/master/functions.php), I'm simply outputting text to indicate that the theme is loaded. [In Travis CI](https://travis-ci.org/mboynes/theme-tests), you can see that [when run as single site, the theme is never loaded](https://travis-ci.org/mboynes/theme-tests/jobs/328816103#L632). [When run as multisite, the theme does get loaded](https://travis-ci.org/mboynes/theme-tests/jobs/328816103#L647).

**Comment by gitlost** [comment]
Thanks for raising the issue @mboynes.

The different behaviour is due to whether certain site transients, in this case `theme_roots`, are loaded or not here https://github.com/WordPress/WordPress/blob/master/wp-includes/option.php#L247.

A simple way to solve it it seems is to filter `theme_root`, PR incoming...

**Comment by mboynes** [comment]
Thanks @gitlost! I was intending on looking into this this AM but you beat me to it. Nice find.
