### ISSUE TITLE
Add function_exists( 'register_block_type' ) check to block.php template

### ISSUE THREAD

**Issue by salcode** [wp-cli/scaffold-command#146]
The block template (`block-php.mustache`) calls the function `register_block_type()`.  This is not a core WordPress function (yet), it is part of Gutenberg.

If you activate your plugin without Gutenberg activated you get a fatal error

> Fatal error: Uncaught Error: Call to undefined function register_block_type()

**Comment by schlessera** [comment]
Hmm...

I'd agree that, given the current circumstances, you would need a `function_exists()` check.

However, this can be considered to be "scaffolding future code", so that check will probably remain even after Gutenberg was merged.

But then again, you might want to activate the plugin on older and newer sites, with the older sites just not having a clean block to use and needing to fall back on a shortcode...

Ok, let's add this, as plugins can still opt to support a pre-Gutenberg world even after the merge.

**Comment by schlessera** [comment]
@salcode Do you care to submit a pull request for the above?

**Comment by schlessera** [comment]
Fied via #147
